version: '3'
services:
  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
    - .:/app/
    ports:
    - "3000:3000"
    links:
    - db
    tty: true
  app:
    build: ./client
    command: ng serve --host 0.0.0.0 --port 4200
    volumes:
    - ./client:/client/
    ports:
    - "4200:4200"
  db:
    image: mysql:5.7.18
    ports:
    - "3306:3306"
    environment:
    - MYSQL_USER=admin
    - MYSQL_DATABASE=api_db
    - MYSQL_PASSWORD=admin
    - MYSQL_ROOT_PASSWORD=root


